# kubectl create secret docker-registry jedlik-gyor-ghcr-io-registry-secret --docker-server=ghcr.io --docker-username=bognarpal --docker-password=************************* --docker-email=bognar.pal@jedlik.eu

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2022-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend2022
  template:
    metadata:
      labels:
        component: backend2022
    spec:
      containers:
        - name: backend
          image: ghcr.io/jedlik-gyor/backend2022:1.0.1
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: jedlik-gyor-ghcr-io-registry-secret

---

apiVersion: v1
kind: Service
metadata:
  name: backend2022-cluster-ip-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    component: backend2022