// <auto-generated />
using System;
using DolgozoNyilvantartas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DolgozoNyilvantartas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200322223302_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DolgozoNyilvantartas.Dolgozo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdoazonositoJel")
                        .IsRequired()
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<string>("Beosztas")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("EvesSzabadsag")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FelvetelDatuma")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.Property<int>("SzervezetiEgysegId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdoazonositoJel")
                        .IsUnique();

                    b.HasIndex("SzervezetiEgysegId");

                    b.ToTable("Dolgozok");
                });

            modelBuilder.Entity("DolgozoNyilvantartas.SzervezetiEgyseg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Nev")
                        .IsUnique();

                    b.ToTable("SzervezetiEgysegek");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nev = "Igazgatóság"
                        },
                        new
                        {
                            Id = 2,
                            Nev = "Termelés"
                        },
                        new
                        {
                            Id = 3,
                            Nev = "Marketing"
                        });
                });

            modelBuilder.Entity("DolgozoNyilvantartas.Dolgozo", b =>
                {
                    b.HasOne("DolgozoNyilvantartas.SzervezetiEgyseg", "SzervezetiEgyseg")
                        .WithMany()
                        .HasForeignKey("SzervezetiEgysegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
